export interface CssVar {
  '--art-theme': string
  '--art-font-color': string
  '--art-background-color': string
  '--art-text-shadow-color': string
  '--art-transition-duration': string
  '--art-padding': string
  '--art-border-radius': string
  '--art-progress-height': string
  '--art-progress-color': string
  '--art-hover-color': string
  '--art-loaded-color': string
  '--art-state-size': string
  '--art-state-opacity': number
  '--art-bottom-height': string
  '--art-bottom-offset': string
  '--art-bottom-gap': string
  '--art-highlight-width': string
  '--art-highlight-color': string
  '--art-control-height': string
  '--art-control-opacity': number
  '--art-control-icon-size': string
  '--art-control-icon-scale': number
  '--art-volume-height': string
  '--art-volume-handle-size': string
  '--art-lock-size': string
  '--art-indicator-scale': number
  '--art-indicator-size': string
  '--art-fullscreen-web-index': 9999
  '--art-settings-icon-size': string
  '--art-settings-max-height': string
  '--art-selector-max-height': string
  '--art-contextmenus-min-width': string
  '--art-subtitle-font-size': string
  '--art-subtitle-gap': string
  '--art-subtitle-bottom': string
  '--art-subtitle-border': string
  '--art-widget-background': string
  '--art-tip-background': string
  '--art-scrollbar-size': string
  '--art-scrollbar-background': string
  '--art-scrollbar-background-hover': string
  '--art-mini-progress-height': string
}
