import type { DefaultOption } from './types'
import { isSafari } from '../utils/compatibility'

export default function createDefaults(): DefaultOption {
  return {
    id: '',
    container: '#artplayer',
    url: '',
    poster: '',
    type: '',
    theme: '#f00',
    volume: 0.7,
    isLive: false,
    muted: false,
    autoplay: false,
    autoSize: false,
    autoMini: false,
    loop: false,
    flip: false,
    playbackRate: false,
    aspectRatio: false,
    screenshot: false,
    setting: false,
    hotkey: true,
    pip: false,
    mutex: true,
    backdrop: true,
    fullscreen: false,
    fullscreenWeb: false,
    subtitleOffset: false,
    miniProgressBar: false,
    useSSR: false,
    playsInline: true,
    lock: false,
    gesture: true,
    fastForward: false,
    autoPlayback: false,
    autoOrientation: false,
    airplay: false,
    proxy: undefined,
    layers: [],
    contextmenu: [],
    controls: [],
    settings: [],
    quality: [],
    highlight: [],
    plugins: [],
    thumbnails: {
      url: '',
      number: 60,
      column: 10,
      width: 0,
      height: 0,
      scale: 1,
    },
    subtitle: {
      url: '',
      type: '',
      style: {},
      name: '',
      escape: true,
      encoding: 'utf-8',
      onVttLoad: vtt => vtt,
    },
    moreVideoAttr: {
      controls: false,
      preload: isSafari ? 'auto' : 'metadata',
    },
    i18n: {},
    icons: {},
    cssVar: {},
    customType: {},
    lang: typeof navigator === 'undefined' ? undefined : navigator?.language.toLowerCase(),
  }
}
