import urlMix from './urlMix';
import attrInit from './attrInit';
import eventInit from './eventInit';
import exclusiveInit from './exclusiveInit';
import playMix from './playMix';
import pauseMix from './pauseMix';
import toggleMix from './toggleMix';
import seekMix from './seekMix';
import volumeMix from './volumeMix';
import currentTimeMix from './currentTimeMix';
import durationMix from './durationMix';
import switchMix from './switchMix';
import playbackRateMix from './playbackRateMix';
import aspectRatioMix from './aspectRatioMix';
import screenshotMix from './screenshotMix';
import fullscreenMix from './fullscreenMix';
import fullscreenWebMix from './fullscreenWebMix';
import fullscreenRotateMix from './fullscreenRotateMix';
import pipMix from './pipMix';
import loadedMix from './loadedMix';
import playedMix from './playedMix';
import playingMix from './playingMix';
import autoSizeMix from './autoSizeMix';
import rectMix from './rectMix';
import flipMix from './flipMix';
import lightMix from './lightMix';
import miniMix from './miniMix';
import loopMin from './loopMin';
import { proxyPropertys } from '../utils';

export default class Player {
    constructor(art) {
        urlMix(art, this);
        eventInit(art, this);
        attrInit(art, this);
        exclusiveInit(art, this);
        playMix(art, this);
        pauseMix(art, this);
        toggleMix(art, this);
        seekMix(art, this);
        volumeMix(art, this);
        currentTimeMix(art, this);
        durationMix(art, this);
        switchMix(art, this);
        playbackRateMix(art, this);
        aspectRatioMix(art, this);
        screenshotMix(art, this);
        fullscreenMix(art, this);
        fullscreenWebMix(art, this);
        fullscreenRotateMix(art, this);
        pipMix(art, this);
        loadedMix(art, this);
        playedMix(art, this);
        playingMix(art, this);
        autoSizeMix(art, this);
        rectMix(art, this);
        flipMix(art, this);
        lightMix(art, this);
        miniMix(art, this);
        loopMin(art, this);
        proxyPropertys(art, this);
    }
}
